#!/bin/bash
intern=eDP1
extern=HDMI-1-2

if xrandr | grep "$extern disconnected"; then
	xrandr --output "$intern" --mode 1920x1080 --output "$extern" --off
#	sed -i 's/HDMI-1-2/eDP1' ~/.config/polybar/config
else
	xrandr --output "$intern" --mode 1920x1080 --pos 0x0 --output "$extern" --primary --mode 1920x1080 --pos 1920x0
#	sed -i 's/eDP1/HDMI-1-2' ~/.config/polybar/config
fi
